package com.project.spring.springsecuritylearn.controller;

import com.project.spring.springsecuritylearn.models.Student;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

@RestController
public class StudentController {

    List<Student> students = new ArrayList<>(List.of(
            new Student(1, "James Bond"),
            new Student(2, "Maria Jones"),
            new Student(3, "Anna Smith")
    ));

    @GetMapping("/students")
    public List<Student> getStudents() {
        return students;
    }

    @GetMapping("/csrf")
    public String getCsrfToken(HttpServletRequest request) {
        return (String) request.getAttribute("_csrf");
    }

    @PostMapping("/students")
    public Student createStudent(@RequestBody Student student) {
        students.add(student);
        return student;
    }
}

// This example is to demonstrate what is a CSRF Token
// CSRF Token is a unique token that is generated by the server and sent to the client.
// The client then sends this token back to the server with every request.
// The server validates this token to ensure that the request is coming from a legitimate source.
// CSRF Token does not work on GET requests, only on POST, PUT, DELETE, etc.
//
// If you hit the URL with GET Method http://localhost:8080/students, you will get the following response:
// List of Students as response
// But if you hit the URL with POST Method http://localhost:8080/students, you will get the following response:
// Response Status 403 Forbidden (even When provided with the corrct spring user creds), CSRF Token is missing
// By default, Spring Security enables CSRF protection. CSRF protection is enabled by default with Spring Security.
